apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "openmaint.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ include "openmaint.adminPassword" . | quote }}
  OPENMAINT_DB_PASSWORD: {{ include "openmaint.appPassword" . | quote }}
